"""initial schema

Revision ID: a5165d673c16
Revises: 
Create Date: 2026-05-18 11:38:02.379516

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a5165d673c16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('page_id', sa.String(length=64), nullable=True),
    sa.Column('page_name', sa.String(length=512), nullable=True),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.String(length=128), nullable=True),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('display_url', sa.String(length=512), nullable=True),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'CAROUSEL', 'UNKNOWN', name='ad_media_type'), nullable=False),
    sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('days_active', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_country'), 'ads', ['country'], unique=False)
    op.create_index(op.f('ix_ads_display_url'), 'ads', ['display_url'], unique=False)
    op.create_index(op.f('ix_ads_is_active'), 'ads', ['is_active'], unique=False)
    op.create_index(op.f('ix_ads_keyword'), 'ads', ['keyword'], unique=False)
    op.create_index(op.f('ix_ads_library_id'), 'ads', ['library_id'], unique=True)
    op.create_index(op.f('ix_ads_page_id'), 'ads', ['page_id'], unique=False)
    op.create_table('client_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=128), nullable=True),
    sa.Column('referral_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_users_email'), 'client_users', ['email'], unique=True)
    op.create_table('parsing_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword', 'country', name='uq_keyword_country')
    )
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('proxy_type', sa.String(length=16), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('rotate_url', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('creatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'CAROUSEL', 'UNKNOWN', name='ad_media_type'), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=True),
    sa.Column('s3_url', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('downloaded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creatives_ad_id'), 'creatives', ['ad_id'], unique=False)
    op.create_index(op.f('ix_creatives_md5'), 'creatives', ['md5'], unique=False)
    op.create_index(op.f('ix_creatives_phash'), 'creatives', ['phash'], unique=False)
    op.create_table('moderation_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='moderation_status'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id')
    )
    op.create_index(op.f('ix_moderation_queue_status'), 'moderation_queue', ['status'], unique=False)
    op.create_table('parsing_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('DISCOVERY', 'REFRESH', name='task_type'), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('ad_id', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DONE', 'FAILED', name='task_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ads_found', sa.Integer(), nullable=False),
    sa.Column('ads_new', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['parsing_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_status_priority_scheduled', 'parsing_tasks', ['status', 'priority', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_status_priority_scheduled', table_name='parsing_tasks')
    op.drop_table('parsing_tasks')
    op.drop_index(op.f('ix_moderation_queue_status'), table_name='moderation_queue')
    op.drop_table('moderation_queue')
    op.drop_index(op.f('ix_creatives_phash'), table_name='creatives')
    op.drop_index(op.f('ix_creatives_md5'), table_name='creatives')
    op.drop_index(op.f('ix_creatives_ad_id'), table_name='creatives')
    op.drop_table('creatives')
    op.drop_table('proxies')
    op.drop_table('parsing_configs')
    op.drop_index(op.f('ix_client_users_email'), table_name='client_users')
    op.drop_table('client_users')
    op.drop_index(op.f('ix_ads_page_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_library_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_keyword'), table_name='ads')
    op.drop_index(op.f('ix_ads_is_active'), table_name='ads')
    op.drop_index(op.f('ix_ads_display_url'), table_name='ads')
    op.drop_index(op.f('ix_ads_country'), table_name='ads')
    op.drop_table('ads')
    op.drop_table('admin_users')
    # ### end Alembic commands ###